[server]
runMode = "debug"
httpPort = 8666
rpcPort = 8667
readTimeout = 20
writeTimeout = 20

[DB]
database = "2019cny_operation"
username = "root"
password = "111111"
host = "172.16.17.121:3306"
maxOpenConn = 100
maxIdleConn = 50

[redis]
maxIdle = 100
timeout = 20
ip = "172.16.17.121"
port = "6379"
password = ""

[mail]
username = ""
password = ""
nickname = "heyHui2018 from github"
mailtype = ""

[MQs]
  [MQs.consume]
  ip = "172.16.125.18"
  port = "5672"
  username = "admin"
  password = "admin"
  host = "/"
  exchange = "best.practise.consume.exchange"
  key = "best.practise.consume.routingKey"
  queue = "best.practise.consume.queue"
  chanRangeNum = 20

  [MQs.publish]
  ip = "172.16.125.18"
  port = "5672"
  username = "admin"
  password = "admin"
  host = "/"
  exchange = "best.practise.publish.exchange"
  key = "best.practise.publish.routingKey"
  queue = "best.practise.publish.queue"
  chanRangeNum = 20

[log]
path = "best-practise.log"
level = "info"

[kafka]
hosts = "172.16.16.114:9092"
topic = "test"
key = "key"

[InfluxDB]
database = "test"
ip = "172.16.16.114"
port = "8086"
username = "test"
password = "test"
retentionPolicy = "default"

[etcd]
endpoints = ["172.16.16.114:2379"]
keys = ["timestamp"]
ip = "172.16.125.18:6667"

[nsqs]
    [nsqs.consume]
    address = "172.16.16.114:4150"
    topic = "c_topic"
    channel = "c_channel"

    [nsqs.publish]
    address = "172.16.16.114:4150"
    topick = "p_topic"
    channel = "p_channel"

[docker]
whiteList = ["test1","test2"]
interval = 60